// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfscbcixatfqtznrbmqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmc2NiY2l4YXRmcXR6bnJibXFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMTk0NjQsImV4cCI6MjA2OTc5NTQ2NH0.4X1gEN_KGuk2E4QqnrGkFIcTEpEC5uhohnU-zCJFohQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});